# Generated by Django 5.0.6 on 2025-02-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_customers_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customers',
            unique_together={('customers_email', 'customers_phone', 'customers_username')},
        ),
    ]
