# Generated by Django 5.0.6 on 2025-02-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customers_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customers_phone',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
