# Generated by Django 5.0.6 on 2025-02-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customers_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customers_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
    ]
