# Generated by Django 5.0.6 on 2025-02-14 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avenues', '0001_initial'),
        ('vendors', '0003_alter_vendorvo_vendors_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesVO',
            fields=[
                ('devices_id', models.AutoField(primary_key=True, serialize=False)),
                ('devices_name', models.CharField(max_length=100)),
                ('devices_mac', models.CharField(max_length=100)),
                ('devices_type', models.BigIntegerField()),
                ('devices_image', models.CharField(max_length=100)),
                ('devices_state', models.CharField(max_length=100)),
                ('devices_status', models.SmallIntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('devices_avenues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avenues.avenuesvo')),
                ('devices_vendors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorvo')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
    ]
