# Generated by Django 5.0.6 on 2025-02-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionsvo',
            name='end_ts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscriptionsvo',
            name='start_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
