# Generated by Django 5.0.6 on 2025-02-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptionsvo_end_ts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionsvo',
            old_name='subscriptions_customers_id',
            new_name='subscriptions_customers',
        ),
        migrations.RenameField(
            model_name='subscriptionsvo',
            old_name='subscriptions_subscriptionsplans_id',
            new_name='subscriptions_subscriptionsplans',
        ),
        migrations.AlterField(
            model_name='subscriptionsvo',
            name='start_ts',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscriptionsvo',
            name='subscriptions_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
