# Generated by Django 5.0.6 on 2025-02-14 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_rename_subscriptions_customers_id_subscriptionsvo_subscriptions_customers_and_more'),
        ('subscriptions_plan', '0002_alter_subscriptionsplanvo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionsvo',
            name='subscriptions_subscriptionsplans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions_plan.subscriptionsplanvo'),
        ),
    ]
