# Generated by Django 5.0.6 on 2025-01-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvenuesVO',
            fields=[
                ('avenues_id', models.AutoField(db_column='avenues_id', primary_key=True, serialize=False)),
                ('avenues_name', models.CharField(db_column='avenues_name', default='', max_length=25, unique=True)),
                ('avenues_username', models.CharField(db_column='avenues_username', default='', max_length=255, unique=True)),
                ('avenues_email', models.CharField(db_column='avenues_email', default='', max_length=30, unique=True)),
                ('avenues_password', models.CharField(db_column='avenues_password', default='', max_length=18, unique=True)),
                ('avenues_address', models.TextField(db_column='avenues_address', default='', max_length=255)),
                ('avenues_slot_price', models.CharField(db_column='avenues_slot_price', default='', max_length=20)),
                ('avenues_logo', models.CharField(db_column='avenues_logo', default='', max_length=255)),
                ('avenues_country', models.CharField(db_column='avenues_country', default='', max_length=30)),
                ('avenues_state', models.CharField(db_column='avenues_state', default='', max_length=30)),
                ('avenues_city', models.CharField(db_column='avenues_city', default='', max_length=30)),
                ('avenues_pincode', models.CharField(db_column='avenues_pincode', default='', max_length=10)),
            ],
            options={
                'db_table': 'avenues_table',
                'unique_together': {('avenues_username', 'avenues_email', 'avenues_password')},
            },
        ),
    ]
