# Generated by Django 5.0.6 on 2025-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avenues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avenuesvo',
            name='avenues_logo',
            field=models.ImageField(blank=True, null=True, upload_to='avenues/'),
        ),
    ]
