# Generated by Django 5.0.6 on 2025-02-15 05:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('vendors', '0004_vendorvo_vendors_avenues'),
        ('zones', '0002_rename_zones_solt_price_zonesvo_zones_slot_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotsVO',
            fields=[
                ('slots_id', models.AutoField(primary_key=True, serialize=False)),
                ('slots_name', models.CharField(max_length=100)),
                ('slots_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('slots_status', models.SmallIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slots_devices', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.devicesvo')),
                ('slots_vendors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorvo')),
                ('slots_zones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.zonesvo')),
            ],
            options={
                'db_table': 'slots',
            },
        ),
    ]
