# Generated by Django 5.0.6 on 2025-02-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionsPlanVO',
            fields=[
                ('id', models.UUIDField()),
                ('subscriptions_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscriptions_plan_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('validity', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due'), ('Canceled', 'Canceled')], max_length=20)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
