# Generated by Django 5.0.6 on 2025-02-13 12:54

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorVO',
            fields=[
                ('vendors_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendors_username', models.CharField(max_length=100)),
                ('vendors_email', models.EmailField(max_length=100)),
                ('vendors_password', models.CharField(max_length=100)),
                ('vendors_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('vendors_address', models.CharField(max_length=100)),
                ('vendors_logo', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'db_table': 'vendors',
                'unique_together': {('vendors_email', 'vendors_phone', 'vendors_username')},
            },
        ),
    ]
