# Generated by Django 5.0.6 on 2025-02-14 06:35

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorvo',
            name='vendors_address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorvo',
            name='vendors_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
