# Generated by Django 5.0.6 on 2025-02-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendorvo_vendors_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorvo',
            name='vendors_phone',
            field=models.CharField(max_length=30),
        ),
    ]
