# Generated by Django 5.0.6 on 2025-02-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendorvo_vendors_avenues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorvo',
            name='vendors_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
