# Generated by Django 5.0.6 on 2025-02-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendorvo_vendors_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorvo',
            name='vendors_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/'),
        ),
    ]
