# Generated by Django 5.0.6 on 2025-02-15 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_alter_customers_customers_phone'),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingVO',
            fields=[
                ('bookings_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookings_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('deleted_ts', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bookings_customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
                ('bookings_slots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.slotsvo')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
