# Generated by Django 5.0.6 on 2025-02-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookingvo',
            table='booking',
        ),
    ]
