# Generated by Django 5.0.6 on 2025-02-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookingvo_end_date_alter_bookingvo_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingvo',
            name='bookings_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
