# Generated by Django 5.0.6 on 2025-02-06 06:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonesVO',
            fields=[
                ('zones_id', models.AutoField(primary_key=True, serialize=False)),
                ('zones_name', models.CharField(max_length=200)),
                ('zones_capacity', models.SmallIntegerField()),
                ('zones_solt_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('zones_floors_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floors.floorsvo')),
            ],
        ),
    ]
