# Generated by Django 5.0.6 on 2025-02-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zonesvo',
            old_name='zones_solt_price',
            new_name='zones_slot_price',
        ),
    ]
